packages:
  taskmanager/Repositories:
    interfaces:
      TaskRepository:
        config:
          dir: "./Tests/mocks"
          filename: "mock_task_repository.go"

      UserRepository:
        config:
          dir: ./Tests/mocks
          filename: "mock_user_repository.go"

  taskmanager/Usecases:
    interfaces:
      TaskUsecase:
        config:
          dir: ./Tests/mocks
          filename: "mock_task_usecase.go"

      UserUsecase:
        config:
          dir: ./Tests/mocks
          filename: "mock_user_usecase.go"
