// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	domain "taskmanager/Domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// DoesUserExist provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) DoesUserExist(ctx context.Context, userName string) (string, string, domain.UserRole, error) {
	ret := _mock.Called(ctx, userName)

	if len(ret) == 0 {
		panic("no return value specified for DoesUserExist")
	}

	var r0 string
	var r1 string
	var r2 domain.UserRole
	var r3 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, string, domain.UserRole, error)); ok {
		return returnFunc(ctx, userName)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, userName)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) string); ok {
		r1 = returnFunc(ctx, userName)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) domain.UserRole); ok {
		r2 = returnFunc(ctx, userName)
	} else {
		r2 = ret.Get(2).(domain.UserRole)
	}
	if returnFunc, ok := ret.Get(3).(func(context.Context, string) error); ok {
		r3 = returnFunc(ctx, userName)
	} else {
		r3 = ret.Error(3)
	}
	return r0, r1, r2, r3
}

// MockUserRepository_DoesUserExist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoesUserExist'
type MockUserRepository_DoesUserExist_Call struct {
	*mock.Call
}

// DoesUserExist is a helper method to define mock.On call
//   - ctx context.Context
//   - userName string
func (_e *MockUserRepository_Expecter) DoesUserExist(ctx interface{}, userName interface{}) *MockUserRepository_DoesUserExist_Call {
	return &MockUserRepository_DoesUserExist_Call{Call: _e.mock.On("DoesUserExist", ctx, userName)}
}

func (_c *MockUserRepository_DoesUserExist_Call) Run(run func(ctx context.Context, userName string)) *MockUserRepository_DoesUserExist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_DoesUserExist_Call) Return(s string, s1 string, userRole domain.UserRole, err error) *MockUserRepository_DoesUserExist_Call {
	_c.Call.Return(s, s1, userRole, err)
	return _c
}

func (_c *MockUserRepository_DoesUserExist_Call) RunAndReturn(run func(ctx context.Context, userName string) (string, string, domain.UserRole, error)) *MockUserRepository_DoesUserExist_Call {
	_c.Call.Return(run)
	return _c
}

// IsDatabaseEmpty provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) IsDatabaseEmpty(ctx context.Context) (bool, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for IsDatabaseEmpty")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (bool, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) bool); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_IsDatabaseEmpty_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDatabaseEmpty'
type MockUserRepository_IsDatabaseEmpty_Call struct {
	*mock.Call
}

// IsDatabaseEmpty is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUserRepository_Expecter) IsDatabaseEmpty(ctx interface{}) *MockUserRepository_IsDatabaseEmpty_Call {
	return &MockUserRepository_IsDatabaseEmpty_Call{Call: _e.mock.On("IsDatabaseEmpty", ctx)}
}

func (_c *MockUserRepository_IsDatabaseEmpty_Call) Run(run func(ctx context.Context)) *MockUserRepository_IsDatabaseEmpty_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_IsDatabaseEmpty_Call) Return(b bool, err error) *MockUserRepository_IsDatabaseEmpty_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserRepository_IsDatabaseEmpty_Call) RunAndReturn(run func(ctx context.Context) (bool, error)) *MockUserRepository_IsDatabaseEmpty_Call {
	_c.Call.Return(run)
	return _c
}

// IsUsernameAvailable provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) IsUsernameAvailable(ctx context.Context, userName string) error {
	ret := _mock.Called(ctx, userName)

	if len(ret) == 0 {
		panic("no return value specified for IsUsernameAvailable")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, userName)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserRepository_IsUsernameAvailable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsUsernameAvailable'
type MockUserRepository_IsUsernameAvailable_Call struct {
	*mock.Call
}

// IsUsernameAvailable is a helper method to define mock.On call
//   - ctx context.Context
//   - userName string
func (_e *MockUserRepository_Expecter) IsUsernameAvailable(ctx interface{}, userName interface{}) *MockUserRepository_IsUsernameAvailable_Call {
	return &MockUserRepository_IsUsernameAvailable_Call{Call: _e.mock.On("IsUsernameAvailable", ctx, userName)}
}

func (_c *MockUserRepository_IsUsernameAvailable_Call) Run(run func(ctx context.Context, userName string)) *MockUserRepository_IsUsernameAvailable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_IsUsernameAvailable_Call) Return(err error) *MockUserRepository_IsUsernameAvailable_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserRepository_IsUsernameAvailable_Call) RunAndReturn(run func(ctx context.Context, userName string) error) *MockUserRepository_IsUsernameAvailable_Call {
	_c.Call.Return(run)
	return _c
}

// PromoteUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) PromoteUser(ctx context.Context, userId string) (domain.User, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for PromoteUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_PromoteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PromoteUser'
type MockUserRepository_PromoteUser_Call struct {
	*mock.Call
}

// PromoteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
func (_e *MockUserRepository_Expecter) PromoteUser(ctx interface{}, userId interface{}) *MockUserRepository_PromoteUser_Call {
	return &MockUserRepository_PromoteUser_Call{Call: _e.mock.On("PromoteUser", ctx, userId)}
}

func (_c *MockUserRepository_PromoteUser_Call) Run(run func(ctx context.Context, userId string)) *MockUserRepository_PromoteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_PromoteUser_Call) Return(user domain.User, err error) *MockUserRepository_PromoteUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserRepository_PromoteUser_Call) RunAndReturn(run func(ctx context.Context, userId string) (domain.User, error)) *MockUserRepository_PromoteUser_Call {
	_c.Call.Return(run)
	return _c
}

// SaveUser provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) SaveUser(ctx context.Context, user domain.User) (domain.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) (domain.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) domain.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_SaveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUser'
type MockUserRepository_SaveUser_Call struct {
	*mock.Call
}

// SaveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *MockUserRepository_Expecter) SaveUser(ctx interface{}, user interface{}) *MockUserRepository_SaveUser_Call {
	return &MockUserRepository_SaveUser_Call{Call: _e.mock.On("SaveUser", ctx, user)}
}

func (_c *MockUserRepository_SaveUser_Call) Run(run func(ctx context.Context, user domain.User)) *MockUserRepository_SaveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserRepository_SaveUser_Call) Return(user1 domain.User, err error) *MockUserRepository_SaveUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockUserRepository_SaveUser_Call) RunAndReturn(run func(ctx context.Context, user domain.User) (domain.User, error)) *MockUserRepository_SaveUser_Call {
	_c.Call.Return(run)
	return _c
}
