// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	domain "taskmanager/Domain"

	mock "github.com/stretchr/testify/mock"
	"go.mongodb.org/mongo-driver/bson"
)

// NewMockTaskRepository creates a new instance of MockTaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskRepository {
	mock := &MockTaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskRepository is an autogenerated mock type for the TaskRepository type
type MockTaskRepository struct {
	mock.Mock
}

type MockTaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskRepository) EXPECT() *MockTaskRepository_Expecter {
	return &MockTaskRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Create(ctx context.Context, task domain.Task) (domain.Task, error) {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Task) (domain.Task, error)); ok {
		return returnFunc(ctx, task)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Task) domain.Task); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Task) error); ok {
		r1 = returnFunc(ctx, task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTaskRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - task domain.Task
func (_e *MockTaskRepository_Expecter) Create(ctx interface{}, task interface{}) *MockTaskRepository_Create_Call {
	return &MockTaskRepository_Create_Call{Call: _e.mock.On("Create", ctx, task)}
}

func (_c *MockTaskRepository_Create_Call) Run(run func(ctx context.Context, task domain.Task)) *MockTaskRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Task
		if args[1] != nil {
			arg1 = args[1].(domain.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_Create_Call) Return(task1 domain.Task, err error) *MockTaskRepository_Create_Call {
	_c.Call.Return(task1, err)
	return _c
}

func (_c *MockTaskRepository_Create_Call) RunAndReturn(run func(ctx context.Context, task domain.Task) (domain.Task, error)) *MockTaskRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Delete(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockTaskRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockTaskRepository_Delete_Call {
	return &MockTaskRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockTaskRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockTaskRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_Delete_Call) Return(err error) *MockTaskRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockTaskRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetAll(ctx context.Context) ([]domain.Task, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Task, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Task); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockTaskRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskRepository_Expecter) GetAll(ctx interface{}) *MockTaskRepository_GetAll_Call {
	return &MockTaskRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *MockTaskRepository_GetAll_Call) Run(run func(ctx context.Context)) *MockTaskRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskRepository_GetAll_Call) Return(tasks []domain.Task, err error) *MockTaskRepository_GetAll_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Task, error)) *MockTaskRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) GetByID(ctx context.Context, id string) (domain.Task, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Task, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Task); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockTaskRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockTaskRepository_GetByID_Call {
	return &MockTaskRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockTaskRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockTaskRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskRepository_GetByID_Call) Return(task domain.Task, err error) *MockTaskRepository_GetByID_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTaskRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string) (domain.Task, error)) *MockTaskRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockTaskRepository
func (_mock *MockTaskRepository) Update(ctx context.Context, id string, updates bson.M) (domain.Task, error) {
	ret := _mock.Called(ctx, id, updates)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bson.M) (domain.Task, error)); ok {
		return returnFunc(ctx, id, updates)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bson.M) domain.Task); ok {
		r0 = returnFunc(ctx, id, updates)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bson.M) error); ok {
		r1 = returnFunc(ctx, id, updates)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockTaskRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - updates bson.M
func (_e *MockTaskRepository_Expecter) Update(ctx interface{}, id interface{}, updates interface{}) *MockTaskRepository_Update_Call {
	return &MockTaskRepository_Update_Call{Call: _e.mock.On("Update", ctx, id, updates)}
}

func (_c *MockTaskRepository_Update_Call) Run(run func(ctx context.Context, id string, updates bson.M)) *MockTaskRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bson.M
		if args[2] != nil {
			arg2 = args[2].(bson.M)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskRepository_Update_Call) Return(task domain.Task, err error) *MockTaskRepository_Update_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTaskRepository_Update_Call) RunAndReturn(run func(ctx context.Context, id string, updates bson.M) (domain.Task, error)) *MockTaskRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
