// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	domain "taskmanager/Domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTaskUsecase creates a new instance of MockTaskUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaskUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaskUsecase {
	mock := &MockTaskUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaskUsecase is an autogenerated mock type for the TaskUsecase type
type MockTaskUsecase struct {
	mock.Mock
}

type MockTaskUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaskUsecase) EXPECT() *MockTaskUsecase_Expecter {
	return &MockTaskUsecase_Expecter{mock: &_m.Mock}
}

// CreateTask provides a mock function for the type MockTaskUsecase
func (_mock *MockTaskUsecase) CreateTask(ctx context.Context, task domain.Task) (domain.Task, error) {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Task) (domain.Task, error)); ok {
		return returnFunc(ctx, task)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.Task) domain.Task); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.Task) error); ok {
		r1 = returnFunc(ctx, task)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskUsecase_CreateTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTask'
type MockTaskUsecase_CreateTask_Call struct {
	*mock.Call
}

// CreateTask is a helper method to define mock.On call
//   - ctx context.Context
//   - task domain.Task
func (_e *MockTaskUsecase_Expecter) CreateTask(ctx interface{}, task interface{}) *MockTaskUsecase_CreateTask_Call {
	return &MockTaskUsecase_CreateTask_Call{Call: _e.mock.On("CreateTask", ctx, task)}
}

func (_c *MockTaskUsecase_CreateTask_Call) Run(run func(ctx context.Context, task domain.Task)) *MockTaskUsecase_CreateTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.Task
		if args[1] != nil {
			arg1 = args[1].(domain.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskUsecase_CreateTask_Call) Return(task1 domain.Task, err error) *MockTaskUsecase_CreateTask_Call {
	_c.Call.Return(task1, err)
	return _c
}

func (_c *MockTaskUsecase_CreateTask_Call) RunAndReturn(run func(ctx context.Context, task domain.Task) (domain.Task, error)) *MockTaskUsecase_CreateTask_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyTask provides a mock function for the type MockTaskUsecase
func (_mock *MockTaskUsecase) ModifyTask(ctx context.Context, id string, updatedTask domain.Task) (domain.Task, error) {
	ret := _mock.Called(ctx, id, updatedTask)

	if len(ret) == 0 {
		panic("no return value specified for ModifyTask")
	}

	var r0 domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.Task) (domain.Task, error)); ok {
		return returnFunc(ctx, id, updatedTask)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, domain.Task) domain.Task); ok {
		r0 = returnFunc(ctx, id, updatedTask)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, domain.Task) error); ok {
		r1 = returnFunc(ctx, id, updatedTask)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskUsecase_ModifyTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyTask'
type MockTaskUsecase_ModifyTask_Call struct {
	*mock.Call
}

// ModifyTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - updatedTask domain.Task
func (_e *MockTaskUsecase_Expecter) ModifyTask(ctx interface{}, id interface{}, updatedTask interface{}) *MockTaskUsecase_ModifyTask_Call {
	return &MockTaskUsecase_ModifyTask_Call{Call: _e.mock.On("ModifyTask", ctx, id, updatedTask)}
}

func (_c *MockTaskUsecase_ModifyTask_Call) Run(run func(ctx context.Context, id string, updatedTask domain.Task)) *MockTaskUsecase_ModifyTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 domain.Task
		if args[2] != nil {
			arg2 = args[2].(domain.Task)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaskUsecase_ModifyTask_Call) Return(task domain.Task, err error) *MockTaskUsecase_ModifyTask_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTaskUsecase_ModifyTask_Call) RunAndReturn(run func(ctx context.Context, id string, updatedTask domain.Task) (domain.Task, error)) *MockTaskUsecase_ModifyTask_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTask provides a mock function for the type MockTaskUsecase
func (_mock *MockTaskUsecase) RemoveTask(ctx context.Context, id string) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTask")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaskUsecase_RemoveTask_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTask'
type MockTaskUsecase_RemoveTask_Call struct {
	*mock.Call
}

// RemoveTask is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskUsecase_Expecter) RemoveTask(ctx interface{}, id interface{}) *MockTaskUsecase_RemoveTask_Call {
	return &MockTaskUsecase_RemoveTask_Call{Call: _e.mock.On("RemoveTask", ctx, id)}
}

func (_c *MockTaskUsecase_RemoveTask_Call) Run(run func(ctx context.Context, id string)) *MockTaskUsecase_RemoveTask_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskUsecase_RemoveTask_Call) Return(err error) *MockTaskUsecase_RemoveTask_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaskUsecase_RemoveTask_Call) RunAndReturn(run func(ctx context.Context, id string) error) *MockTaskUsecase_RemoveTask_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveAllTasks provides a mock function for the type MockTaskUsecase
func (_mock *MockTaskUsecase) RetrieveAllTasks(ctx context.Context) ([]domain.Task, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveAllTasks")
	}

	var r0 []domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]domain.Task, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []domain.Task); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskUsecase_RetrieveAllTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveAllTasks'
type MockTaskUsecase_RetrieveAllTasks_Call struct {
	*mock.Call
}

// RetrieveAllTasks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTaskUsecase_Expecter) RetrieveAllTasks(ctx interface{}) *MockTaskUsecase_RetrieveAllTasks_Call {
	return &MockTaskUsecase_RetrieveAllTasks_Call{Call: _e.mock.On("RetrieveAllTasks", ctx)}
}

func (_c *MockTaskUsecase_RetrieveAllTasks_Call) Run(run func(ctx context.Context)) *MockTaskUsecase_RetrieveAllTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTaskUsecase_RetrieveAllTasks_Call) Return(tasks []domain.Task, err error) *MockTaskUsecase_RetrieveAllTasks_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockTaskUsecase_RetrieveAllTasks_Call) RunAndReturn(run func(ctx context.Context) ([]domain.Task, error)) *MockTaskUsecase_RetrieveAllTasks_Call {
	_c.Call.Return(run)
	return _c
}

// RetrieveTaskByID provides a mock function for the type MockTaskUsecase
func (_mock *MockTaskUsecase) RetrieveTaskByID(ctx context.Context, id string) (domain.Task, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RetrieveTaskByID")
	}

	var r0 domain.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.Task, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.Task); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Task)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaskUsecase_RetrieveTaskByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RetrieveTaskByID'
type MockTaskUsecase_RetrieveTaskByID_Call struct {
	*mock.Call
}

// RetrieveTaskByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockTaskUsecase_Expecter) RetrieveTaskByID(ctx interface{}, id interface{}) *MockTaskUsecase_RetrieveTaskByID_Call {
	return &MockTaskUsecase_RetrieveTaskByID_Call{Call: _e.mock.On("RetrieveTaskByID", ctx, id)}
}

func (_c *MockTaskUsecase_RetrieveTaskByID_Call) Run(run func(ctx context.Context, id string)) *MockTaskUsecase_RetrieveTaskByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaskUsecase_RetrieveTaskByID_Call) Return(task domain.Task, err error) *MockTaskUsecase_RetrieveTaskByID_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockTaskUsecase_RetrieveTaskByID_Call) RunAndReturn(run func(ctx context.Context, id string) (domain.Task, error)) *MockTaskUsecase_RetrieveTaskByID_Call {
	_c.Call.Return(run)
	return _c
}
