// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	domain "taskmanager/Domain"

	mock "github.com/stretchr/testify/mock"
)

// NewMockUserUsecase creates a new instance of MockUserUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserUsecase {
	mock := &MockUserUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserUsecase is an autogenerated mock type for the UserUsecase type
type MockUserUsecase struct {
	mock.Mock
}

type MockUserUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserUsecase) EXPECT() *MockUserUsecase_Expecter {
	return &MockUserUsecase_Expecter{mock: &_m.Mock}
}

// AuthenticateUser provides a mock function for the type MockUserUsecase
func (_mock *MockUserUsecase) AuthenticateUser(ctx context.Context, userName string, password string) (string, error) {
	ret := _mock.Called(ctx, userName, password)

	if len(ret) == 0 {
		panic("no return value specified for AuthenticateUser")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, userName, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, userName, password)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userName, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUsecase_AuthenticateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthenticateUser'
type MockUserUsecase_AuthenticateUser_Call struct {
	*mock.Call
}

// AuthenticateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userName string
//   - password string
func (_e *MockUserUsecase_Expecter) AuthenticateUser(ctx interface{}, userName interface{}, password interface{}) *MockUserUsecase_AuthenticateUser_Call {
	return &MockUserUsecase_AuthenticateUser_Call{Call: _e.mock.On("AuthenticateUser", ctx, userName, password)}
}

func (_c *MockUserUsecase_AuthenticateUser_Call) Run(run func(ctx context.Context, userName string, password string)) *MockUserUsecase_AuthenticateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserUsecase_AuthenticateUser_Call) Return(s string, err error) *MockUserUsecase_AuthenticateUser_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserUsecase_AuthenticateUser_Call) RunAndReturn(run func(ctx context.Context, userName string, password string) (string, error)) *MockUserUsecase_AuthenticateUser_Call {
	_c.Call.Return(run)
	return _c
}

// PromoteUser provides a mock function for the type MockUserUsecase
func (_mock *MockUserUsecase) PromoteUser(ctx context.Context, userId string) (domain.User, error) {
	ret := _mock.Called(ctx, userId)

	if len(ret) == 0 {
		panic("no return value specified for PromoteUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.User, error)); ok {
		return returnFunc(ctx, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.User); ok {
		r0 = returnFunc(ctx, userId)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUsecase_PromoteUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PromoteUser'
type MockUserUsecase_PromoteUser_Call struct {
	*mock.Call
}

// PromoteUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userId string
func (_e *MockUserUsecase_Expecter) PromoteUser(ctx interface{}, userId interface{}) *MockUserUsecase_PromoteUser_Call {
	return &MockUserUsecase_PromoteUser_Call{Call: _e.mock.On("PromoteUser", ctx, userId)}
}

func (_c *MockUserUsecase_PromoteUser_Call) Run(run func(ctx context.Context, userId string)) *MockUserUsecase_PromoteUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserUsecase_PromoteUser_Call) Return(user domain.User, err error) *MockUserUsecase_PromoteUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserUsecase_PromoteUser_Call) RunAndReturn(run func(ctx context.Context, userId string) (domain.User, error)) *MockUserUsecase_PromoteUser_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterUser provides a mock function for the type MockUserUsecase
func (_mock *MockUserUsecase) RegisterUser(ctx context.Context, userName string, password string) (domain.User, error) {
	ret := _mock.Called(ctx, userName, password)

	if len(ret) == 0 {
		panic("no return value specified for RegisterUser")
	}

	var r0 domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (domain.User, error)); ok {
		return returnFunc(ctx, userName, password)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) domain.User); ok {
		r0 = returnFunc(ctx, userName, password)
	} else {
		r0 = ret.Get(0).(domain.User)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userName, password)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserUsecase_RegisterUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterUser'
type MockUserUsecase_RegisterUser_Call struct {
	*mock.Call
}

// RegisterUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userName string
//   - password string
func (_e *MockUserUsecase_Expecter) RegisterUser(ctx interface{}, userName interface{}, password interface{}) *MockUserUsecase_RegisterUser_Call {
	return &MockUserUsecase_RegisterUser_Call{Call: _e.mock.On("RegisterUser", ctx, userName, password)}
}

func (_c *MockUserUsecase_RegisterUser_Call) Run(run func(ctx context.Context, userName string, password string)) *MockUserUsecase_RegisterUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserUsecase_RegisterUser_Call) Return(user domain.User, err error) *MockUserUsecase_RegisterUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserUsecase_RegisterUser_Call) RunAndReturn(run func(ctx context.Context, userName string, password string) (domain.User, error)) *MockUserUsecase_RegisterUser_Call {
	_c.Call.Return(run)
	return _c
}
